- source/includes/20170710/resources/_assignments.md.erb
- source/includes/20170710/resources/_level_progressions.md.erb
- source/includes/20170710/resources/_resets.md.erb
- source/includes/20170710/resources/_review_statistics.md.erb
- source/includes/20170710/resources/_reviews.md.erb
- source/includes/20170710/resources/_study_materials.md.erb
- source/includes/20170710/resources/_subjects.md.erb
- source/includes/20170710/resources/_user.md.erb
* Add information about new subject attribute `lesson_position`
* Order table rows by alphabetical
---
> Add subject lesson position details

- source/examples/_PUT_javascript.erb
- source/examples/_PUT_shell.erb
- source/includes/20170710/resources/_user.md.erb
* Added information about preferences under `/user`
---
> Add user preferences information

- source/examples/_PUT_javascript.erb
- source/examples/_PUT_shell.erb
- source/includes/20170710/resources/_assignments.md.erb
NOTE: Relies on #4 
* Added PUT `/assignment/:id/learned`. Used to update state of assignments from lesson to review 
---
> Added /assignment/:id/learned

- source/includes/20170710/resources/_study_materials.md.erb
NOTE: Relies on #4 
* Added POST /study_materials and PUT /study_materials/:id
---
> Add POST /study_materials and PUT /study_materials/:id

- source/includes/20170710/resources/_subjects.md.erb
* Fix a typo in the auxiliary meaning structure of the example radical response
* Sort example response attributes and a couple tables of attributes alphabetically
---
> Fix typo with radical auxiliary meanings; sort lists alphabetically

- source/includes/20170710/getting_started/_errors.md
* Added 403 error code to documentation
---
> Added 403 error code to documentation

- source/includes/20170710/resources/_user.md.erb
* Add default_voice_actor to user.preferences
---
> Add default_voice_actor to user.preferences

- source/includes/20170710/resources/_assignments.md.erb
* Drop `assignments.resurrected` since it is redundant. `assignments.resurrected_at` already exists. Checking the presence of the value provides the same information.
---
> Drop assignments resurrected

- source/includes/20170710/resources/_assignments.md.erb
- source/includes/20170710/resources/_level_progressions.md.erb
- source/includes/20170710/resources/_user.md.erb
* Remove top level `subscribed` since it has been replaced by `subscription.active`
* Remove top level `max_level_granted_by_subscription` since it has been replaced by `subscription.max_level_granted`
---
> Remove deprecated subscription fields from `GET /user`

- source/20170710/index.html.md
- source/includes/20170710/getting_started/_authentication.md.erb
* fix: link to https://www.wanikani.com/settings/personal_access_tokens, not the old token page
* fix: change `documentation_root_path` variable to fix 3 links: the title in the sidebar, and 2 references to `current_page.data.documentation_root_path`
---
> fix(urls): fix a few links

- source/includes/20170710/resources/_subjects.md.erb
> Fix a typo with the component_subject_ids description

- source/includes/20170710/_introduction.md
- source/includes/20170710/getting_started/_revisions.md.erb
* Remove beta notices since [API version 2 is moving out of beta](https://community.wanikani.com/t/api-version-2-moving-out-of-beta-sunsetting-api-version-1/42539).
---
> Remove beta notices

- source/20170710/index.html.md
- source/includes/20170710/getting_started/_response_structure.md
- source/includes/20170710/resources/_assignments.md.erb
- source/includes/20170710/resources/_reviews.md.erb
- source/includes/20170710/resources/_spaced_repetition_systems.md.erb
- source/includes/20170710/resources/_srs_stages.md.erb
- source/includes/20170710/resources/_subjects.md.erb
- source/includes/20170710/resources/_voice_actors.md.erb
* Add /spaced_repetition_systems endpoint details
* Add `spaced_repetition_system_id` details on Subject and Reviews
* Add deprecation warnings for /srs_stages
* Add deprecation warnings for `assignment.srs_stage_name`, `review.starting_srs_stage_name`, and `review.ending_srs_stage_name`.
* Minor typos and corrections
---
> Add /spaced_repetition_systems

- source/includes/20170710/resources/_assignments.md.erb
* Add deprecation warning about the removal of `assignment.passed`
---
> Remove assignment.passed

- source/includes/20170710/_additional_information.md
- source/includes/20170710/best_practices/_caching.md
- source/includes/20170710/getting_started/_pagination.md
- source/includes/20170710/resources/_assignments.md.erb
- source/includes/20170710/resources/_level_progressions.md.erb
- source/includes/20170710/resources/_reviews.md.erb
- source/includes/20170710/resources/_subjects.md.erb
* Fix typos and broken links, add missing details
* Add metadata details for radical.character_images metadata
---
> fix(docs): Fix typos and broken links, add missing details

- source/includes/20170710/resources/_assignments.md.erb
* Add edge case documentation for Get All Assigments endpoint, re: assignments for subjects that have moved above a user's current level
---
> fix(docs): add missing detail about assignments possibly being available for subjects above user's level

- source/includes/20170710/resources/_assignments.md.erb
It's possible that hidden isn't present and this may be unexpected. This will clarify it.
* Acknowledges that the hidden field may not exist in the assignment data structure.
---
> Mark hidden as an optional field

- source/includes/20170710/getting_started/_response_structure.md
Collection responses can have a null value if no resources are returned. I have updated this information
* added nullability information
---
> fix(docs): Added nullability information to collection data_updated_at.

- source/includes/20170710/getting_started/_rate_limit.md
* Add details about available `RateLimit-*` headers
---
> Add details about `RateLimit-*` headers

- source/includes/20170710/resources/_subjects.md.erb
Closes https://github.com/tofugu/engineering-issues/issues/345
---
> Fix: Missing commas in documentation

- source/includes/20170710/resources/_reviews.md.erb
As this endpoint doesn't return any data at the moment and we have had a few users make comments about this documentation being out of date, I am updating the documentation to reflect the current state of play.  We can revert this commit when / if things change.
---
> update 'all reviews' warning to indicate no data is returned

- source/includes/20170710/resources/_subjects.md.erb
This PR updates the api docs to remove any reference to png images being used for character images.  See https://www.notion.so/tofugu/Tidy-Up-Radical-Images-cbd7c8f3458949ddb055a75c942e7be5?pvs=4 for relevant discussions and links.
---
> remove mention of png character_images

- source/includes/20170710/resources/_user.md.erb
We no longer support lesson_presentation_order so updating the api docs accordingly.
---
> Deprecate lessons_presentation_order

- source/includes/20170710/resources/_user.md.erb
This PR updates the api docs to deprecate the `default_voice_actor_id` user preference.  This preference has now been replaced by `preferred_voice_actor_type` which will not be exposed in the API.
---
> deprecate default_voice_actor_id

- source/includes/20170710/resources/_assignments.md.erb
A user pointed out the following via support on Front.
> I think there's a mistake in the API example [Assignments Available for Review in Two Hours](https://docs.api.wanikani.com/20170710/#assignments-available-for-review-in-two-hours).
The query parameter used in that example "available_after=<2 hours from now>" would return the set of assignments that will not be available in two hours but will become available at some time after that. 
To return all assignments that will be available by two hours from now (including assignments that are already available now), the query parameter should be "available_before=<2 hours from now>".
If the intent is to exclude assignments that are available now and return only those assignments that will become available in the next two hours, the query …
> fix assignments example

- source/includes/20170710/resources/_assignments.md.erb
The `started_at` parameter needs to be nested under `assignment`. This has always been the implementation. Unfortunately the documentation misrepresented this.
> Fix: Assignment's `start` endpoint examples misrepresents the shape of the request body
